# SourceRPG release 2.0.0 by Steven Hartin
# ./sourcerpg/addons/sourcerpg_admin/sourcerpg_admin.py

#################################
#### DO NOT EDIT THIS FILE, #####
####    IF YOU DO, THINGS   #####
####   THINGS COULD BREAK   #####
#################################
import es

import os

from sourcerpg import sourcerpg

from sqlite3 import dbapi2 as sqlite
from shutil import move

""" Import the psyco module which improves speed """
import psyco
psyco.full()

